### ISSUE TITLE
Token issues breaking workshop

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium-workshop#9]
If you just open the workshop right now, you'll see a black overlay preventing you from interacting with the app.

This is because the main tileset hasn't loaded yet, and the overlay is a loading indicator. However, the tileset will never load because it looks like the default token here has expired?

But that's okay! You can add in your own token by replacing:

```
Cesium.Ion.defaultAccessToken = '<YOUR ACCESS TOKEN HERE>';
```

So then most things load (imagery etc) **but not the tileset id 3839** presumably because my account doesn't have access to it?

So the loading indicator never goes away either way.

**Comment by hpinkos** [comment]
Fixed.  We need to make sure we keep updating the version of CesiumJS used in this repo.  I added a note as part of our release process.

**Comment by OmarShehata** [comment]
This is still broken though. If you follow the tutorial and put your asset token where it tells you, the NYC dataset will fail to load, the loading indicator never goes away, and no error is shown on screen.

The solution is to add the NYC tileset to the asset depot. Otherwise you can't really follow the tutorial.

**Comment by hpinkos** [comment]
Thanks @OmarShehata, I forgot that was an issue as well.  I opened another issue
